# Render Blueprint ─ deploys a managed MongoDB instance,
# a Docker-based Node/Express backend, and a static-site Vite frontend.

databases:
  - name: edustream-mongo          # Render-managed Mongo cluster
    databaseName: edustream        # initial DB created for you
    plan: free                     # upgrade later if you need more storage
    ipAllowList: []                # empty ⇒ only Render services can reach it

services:
  # ─────────── Backend ───────────
  - type: web
    name: edustream-backend
    env: docker
    plan: free                     # “Starter” / paid is optional
    dockerfilePath: Backendtemplate/Dockerfile
    dockerContext: ./Backendtemplate
    autoDeploy: true               # redeploy on every git push
    envVars:
      - key: PORT
        value: "8080"
      - key: MONGODB_URI           # inject managed DB connection string
        fromDatabase:
          name: edustream-mongo
          property: connectionString
      # ─── your secrets (placeholders, set real values in the dashboard) ───
      - key: ACCESS_TOKEN_SECRET
        value: "CHANGEME"
      - key: REFRESH_TOKEN_SECRET
        value: "CHANGEME"
      - key: TWILIO_ACCOUNT_SID
        value: "CHANGEME"
      - key: TWILIO_AUTH_TOKEN
        value: "CHANGEME"
      - key: TWILIO_PHONE_NUMBER
        value: "CHANGEME"
      - key: GEMINI_API_KEY
        value: "CHANGEME"
      - key: CLIENT_URL
        value: https://edustream-frontend-static.onrender.com

  # ─────────── Frontend (static site) ───────────
  - type: web
    name: edustream-frontend-static
    runtime: static
    rootDir: Frontend              # folder containing the frontend code
    buildCommand: npm ci && npm run build
    staticPublishPath: dist        # Vite’s default output folder
    envVars:
      - key: VITE_BASE_URL
        value: https://edustream-backend-8iyx.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html