databases:
  - name: edustream-mongo
    databaseName: edustream
    plan: free
    ipAllowList: []

services:
  - type: web
    name: edustream-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Backendtemplate/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        fromDatabase:
          name: edustream-mongo
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://edustream-frontend.onrender.com

  - type: web
    name: edustream-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    rootDir: Frontend
    envVars:
      - key: VITE_BASE_URL
        value: https://edustream-backend.onrender.com/api/v1