# Render Blueprint: deploys MongoDB, backend (Docker), and frontend (static site)
# Docs: https://render.com/docs/infrastructure-as-code

databases:
  - name: edustream-mongo
    databaseName: edustream
    plan: free
    ipAllowList: []

services:
  # Backend: Node/Express API built from Dockerfile
  - type: web
    name: edustream-backend
    env: docker
    plan: free
    dockerfilePath: ./Backendtemplate/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        fromDatabase:
          name: edustream-mongo
          property: connectionString
      - key: ACCESS_TOKEN_SECRET
        value: "CHANGEME"
      - key: REFRESH_TOKEN_SECRET
        value: "CHANGEME" 
      - key: TWILIO_ACCOUNT_SID
        value: "CHANGEME"
      - key: TWILIO_AUTH_TOKEN
        value: "CHANGEME"
      - key: TWILIO_PHONE_NUMBER
        value: "CHANGEME"
      - key: GEMINI_API_KEY
        value: "CHANGEME"
      - key: CLIENT_URL
        value: "https://edustream-frontend.onrender.com"

staticSites:
  - name: edustream-frontend
    buildCommand: npm ci && npm run build
    publishPath: dist
    rootDir: Frontend
    envVars:
      - key: VITE_BASE_URL
        value: "https://edustream-backend.onrender.com/api/v1"